// Generated by Wrangler on Thu Sep 05 2024 15:01:18 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	SESSION_SECRET: string;
	FATHOM_ID: string;
	CK_API_KEY: string;
	CK_MEMBER_FORM: string;
	CK_APPRENTICE_FORM: string;
	HONEYPOT_SECRET: string;
	INTERNAL_COMMAND_TOKEN: string;
	ALLOW_INDEXING: string;
	BUCKET: R2Bucket;
	DB: D1Database;
}
